function init(self)
    msg.post("@render:", "zoom",        {zoom=1})
    msg.post("@render:", "clear_color", {color=vmath.vector4(0.5,0.5,0.5,1)})
    msg.post("@render:", "disable_stencil_mask")
    
end

function update(self, dt)
    -- Add update code here
    -- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
    -- Add message-handling code here
    -- Remove this function if not needed
end
